services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["sh", "-c", "python load_data_to_db.py & flask run --host=0.0.0.0"]

  db:
    image: postgres:15-alpine
    container_name: challenge-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pg_data: